# Generated by Django 2.2.13 on 2020-06-10 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields
import researchers.models
import researchers.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(max_length=255)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Article Group',
            },
        ),
        migrations.CreateModel(
            name='DatasetArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors', djongo.models.fields.ArrayField(model_container=researchers.models.Author, null=True)),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField(blank=True, null=True)),
                ('keywords', djongo.models.fields.ArrayField(model_container=researchers.models.Keyword)),
                ('summary', models.TextField()),
                ('published_date', models.DateTimeField(null=True)),
                ('pdf_link', models.CharField(max_length=255)),
                ('relation_score', models.FloatField(blank=True, null=True)),
                ('similarity_score', models.FloatField(blank=True, null=True)),
                ('article_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='researchers.ArticleGroup')),
            ],
            options={
                'verbose_name': 'Dataset Article',
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField(null=True)),
                ('relation_score', models.FloatField(null=True)),
                ('article_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Article', to='researchers.ArticleGroup')),
                ('recommended_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='researchers.DatasetArticle')),
            ],
            options={
                'verbose_name': 'Recommendation',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField(blank=True, null=True)),
                ('keywords', djongo.models.fields.ArrayField(model_container=researchers.models.Keyword)),
                ('file', models.FileField(upload_to=researchers.models.user_directory_path, validators=[researchers.validators.validate_file_extension])),
                ('article_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='researchers.ArticleGroup')),
            ],
            options={
                'verbose_name': 'Article',
            },
        ),
    ]
